import apiClient from './apiClient';
export const getDriverTripsApi = () => apiClient.get('/driver/trips');
export const startTripApi = (id) => apiClient.put(`/driver/trips/${id}/start`);
export const completeTripApi = (id) => apiClient.put(`/driver/trips/${id}/complete`);
export const cancelTripApi  = (id) => apiClient.put(`/driver/trips/${id}/cancel`);
export const getPassengerListApi = (tripId) => apiClient.get(`/driver/trips/${tripId}/passengers`);
export const getEarningsApi = () => apiClient.get('/driver/earnings');
export const getDriverVehicleApi = () => apiClient.get('/driver/vehicle');
export const scheduleServiceApi = (data) => apiClient.post('/driver/service-request', data);
export const reportIssueApi = (data) => apiClient.post('/driver/issues', data);
export const sendEmergencyApi = (data) => apiClient.post('/driver/emergency', data);
export const updateLocationApi = (data) => apiClient.post('/driver/location', data);
export const submitChecklistApi   = (tripId, data)           => apiClient.post(`/driver/trips/${tripId}/checklist`, data);
export const scanQrApi            = (token, tripId)          => apiClient.post('/driver/scan-qr', { token, trip_id: tripId ?? null });
export const markStopArrivalApi   = (tripId, stopId)         => apiClient.post(`/driver/trips/${tripId}/stops/${stopId}/arrive`);
export const reportDelayApi       = (tripId, data)           => apiClient.post(`/driver/trips/${tripId}/delay`, data);
export const getDriverNotificationsApi = (userId)            => apiClient.get(`/notifications/user/${userId}`).then(r => r.data);
export const markNotificationReadApi   = (notifId)           => apiClient.put(`/notifications/${notifId}/read`, {}).then(r => r.data);
export const getRouteWaypointsApi      = (routeId)           => apiClient.get(`/routes/${routeId}/waypoints`).then(r => r.data);
export const getRouteStopsApi          = (routeId)           => apiClient.get(`/routes/${routeId}/stops`).then(r => r.data);
export const getDriverRatingsApi       = (driverId)          => apiClient.get(`/ratings/driver?driver_id=${driverId}`).then(r => r.data);